### PR TITLE
Validate boolean parameters in /_replicate payload

### PR DESCRIPTION
**Pull request by eiri**
Unlike `/_replicator`, end-point `/_replicate` doesn't check type for the boolean parameters in payload, which leads replicator to crash with `case_clause`.

This patch makes it to return "bad request" error on invalid input.

COUCHDB-3118

### CODE REVIEW

**Comment by iilyak** [comment]
All tests pass locally. +1
```
======================== EUnit ========================
module 'json_stream_parse'
module 'couch_replicator_worker'
module 'couch_replicator_utils'
  ......
  couch_replicator_utils: check_convert_options_pass_test...[0.021 s] ok
  couch_replicator_utils: check_convert_options_fail_test...ok
  [done in 0.040 s]
  ......
      [done in 9.362 s]
    [done in 34.282 s]
  [done in 34.282 s]
=======================================================
  All 168 tests passed.
==> rel (eunit)
==> db.test (eunit)
```

**Comment by nickva** [comment]
+1

**Comment by rnewson** [comment]
please remember that couchdb is frozen for the 2.0 release, please stop merging new features or fixing that aren't 2.0 blockers.

@nickva @eiri @iilyak

**Comment by kxepal** [comment]
@rnewson Why not to create a branch for 2.0 and prepare release from there while people still can work on new features and master? Sounds like gitflow-ish.

**Comment by rnewson** [comment]
Committers to couchdb should be focused on making 2.0 happen. If they want to do other, unrelated work, they can keep it elsewhere for now.

**Pull request merged**
