### PR TITLE
Handle case when replication param "doc_ids": "null"

### PR DESCRIPTION
**Pull request by jaydoane**
BugzID: 48602

### CODE REVIEW

**Comment by kxepal** [comment]
Why `null` could be passed as `"null"`? I think the error is on client side that sends such request, isn't it?

**Comment by jaydoane** [comment]
Yes, it seems like this is a special case for clients who do not understand that "null" != null. Still, returning a 500 doesn't seem very friendly.

**Comment by kxepal** [comment]
Right, HTTP 400 looks as more correct one. Technically, such clients cannot implement JSON properly which means that there are more other places where they may hit the same issue (like views). Should we care about them?

P.S. Also wonder what are these clients if it's not a top secret (:

**Comment by rnewson** [comment]
hrm, I don't think we should silently ignore junk input. There's no precedent in this function for sending a 400 bad request, but I think that's the right status code if we're improving this at all.

I note that other params that need numbers use couch_util:to_integer which will also function_clause if given something unexpected.

**Comment by jaydoane** [comment]
AFAICT, there's no specific client that is sending this, but it was apparently discovered in testing.

The internal Cloudant bug that this PR attempts to address claims it was "fixed in couchdb" and refers to
https://git-wip-us.apache.org/repos/asf?p=couchdb.git;a=commitdiff;h=bea76dbf
But of course, that only fixes the "doc_ids":null case, not the specific case this bug report is calling out.

**Comment by janl** [comment]
This is a nice “oh they have thought of *that*” kind of thing, kinda like http://blog.couchdb.org/2014/04/08/the-little-things1-do-not-delete/

**Comment by kxepal** [comment]
@janl Those who works in such way with HTTP deserves to suffer, that's fine (:  That was acceptable in wild-wild 90x, but today is 2015.

**Comment by jaydoane** [comment]
It seems like the fundamental issue is that "null" is a string, but we're expecting an array. My inclination would be to return a response code 400 with the payload {"error":"parameter \`doc_ids\` must be an array"}.

To make this work, we presumably change the function clause to this:
```
convert_options([{<<"doc_ids">>, V} | _R]) when not is_list(V) ->
    throw({bad_request, <<"parameter `doc_ids` must be an array">>});
```
but unfortunately, this also requires adding this additional try clause to chttpd_misc:handle_replicate_req:
```
    {bad_request, Reason} ->
        send_json(Req, 400, {[{error, Reason}]});
```
to avoid sending the client a 500 try_clause error.

Does this seem like the correct approach?

**Comment by jaydoane** [comment]
As an aside, it seems like a more declarative approach to error handling might be desirable.

**Comment by jaydoane** [comment]
The follow-up PR: https://github.com/cloudant/chttpd-local/pull/15

**Comment by kxepal** [comment]
@jaydoane https://github.com/cloudant/chttpd-local/pull/15 - 404 not found. Anything important there?

**Comment by jaydoane** [comment]
@kxepal, I have closed the obsolete https://github.com/cloudant/chttpd-local/pull/15 and opened https://github.com/apache/couchdb-chttpd/pull/83, which applies the same patch onto the relevant ASF repo

**Comment by jaydoane** [comment]
@kxepal, I rebased, and tested against latest chttpd to ensure it still works. Seeing:
```
$ curl http://127.0.0.1:15984/_replicate -u adm:pass -H 'Content-Type: application/json' -X POST -d ' {"source": "foo", "target": "bar", "doc_ids": "null"} '
{"error":"bad_request","reason":"parameter `doc_ids` must be an array"}
```
Can this be merged now?

**Comment by kxepal** [comment]
@jaydoane done. Thanks! (:

**Comment by kxepal** [comment]
Erhm, fixed via 437c6571f. You can close this PR.

**Comment by jaydoane** [comment]
@kxepal, thank you!

Also, looks like we need to create .travis.yml for this repo?

**Pull request closed without merging**
