### PR TITLE
revert cdf8949 (couch_util:rfc1123_date)

### PR DESCRIPTION
**Pull request by robertkowalski**
this got fixed in R14B02 as OTP-9087

COUCHDB-627

### CODE REVIEW

**Comment by kxepal** [comment]
But we [support](https://github.com/apache/couchdb/blob/master/rebar.config.script#L70) R14B01 as well...

**Comment by robertkowalski** [comment]
wow I did not expect that - R14B01 is from 2010 - it is 5 years old

hmmm

**Comment by robertkowalski** [comment]
@kxepal do you think we should support R14B01 further? I just checked travis and we are not testing `R14B01` in our test matrix

**Comment by kxepal** [comment]
@robertkowalski it's up to @rnewson . For me there is no sense (R14B04 is better on this position), but he had some reasons for it support.

**Comment by rnewson** [comment]
Let's drop R14B01 support after 2.0 ships.

**Comment by rnewson** [comment]
Actually, probably all R14 series.

**Comment by kxepal** [comment]
@rnewson +1

**Comment by kxepal** [comment]
@robertkowalski We eventually dropped R14 support before 2.0 release (: Would you like to merge this?

**Comment by robertkowalski** [comment]
couch does not compile any more for me:

```
Cloning into 'couch_epi'...
ERROR: Failed to extract name from /Users/robert/apache/couchdb/src/couch_epi/src/couch_epi.app.src.script: {error,
                                                                                                             {error,
                                                                                                              {15,
                                                                                                               file,
                                                                                                               {error,
                                                                                                                {badmatch,
                                                                                                                 {error,
                                                                                                                  enoent}},
                                                                                                                [{erl_eval,
                                                                                                                  expr,
                                                                                                                  3,
                                                                                                                  []}]}}}}
ERROR: 'get-deps' failed while processing /Users/robert/apache/couchdb: rebar_abort
```

feel free to merge this patch when couch compiles again

**Comment by kxepal** [comment]
@robertkowalski ensure your couchdb is latest @ update all the deps @ try again

**Comment by robertkowalski** [comment]
ah i c

**Comment by robertkowalski** [comment]
merged as 3ce785710e28222064bfcfd68d7fd0af96b72add

thanks for the hint!

**Pull request closed without merging**
