### PR TITLE
Inject random delays in scan_all_dbs

### PR DESCRIPTION
**Pull request by iilyak**
couch_replication_server scans filesystem to find all _replication
databases. For every database found it does

    gen_server:cast(Server, {resume_scan, DbName})

Extract independent process where we do gen_server:cast after a random delay.
This effectively removes stampede and randomizes the order in which we
process _replication databases.

COUCHDB-3088

### CODE REVIEW

**Comment by kxepal** [comment]
That is the [second](https://github.com/apache/couchdb-couch-replicator/pull/37) jitter implementation within the same module. May be generalize somehow that concept?

**Comment by iilyak** [comment]
Maybe. I was trying to but it is not that straight forward. I'll try again using a different approach.

**Comment by iilyak** [comment]
@kxepal: Updated to avoid doing the same calculation in two places.

**Comment by kxepal** [comment]
@iilyak Looks good except that [here](https://github.com/cloudant/couchdb-couch-replicator/blob/a3b7158a9dc9f1243d84c2e77dc18b8ef24eae30/src/couch_replicator_manager.erl#L130) we'll crash to call undefined function.

**Comment by iilyak** [comment]
Oops

**Comment by iilyak** [comment]
@kxepal: The commit has been updated

**Comment by kxepal** [comment]
Thanks! LGFM.

**Comment by nickva** [comment]
@iilyak why not use spawn_link, wonder if that would be better?

**Comment by nickva** [comment]
Given that replicator_manager is a single bottleneck and will process requests serially anyway (so if it is blocked, `resume,...` messages will be queued up in its mailbox) if it is worth just inserting a predictable sleep based on Acc right inside the scan_all_dbs? Or do you think there is an advantage to quickly parsing the file systems and spawning waiter processes?

**Comment by iilyak** [comment]
@nickva: We cannot put delays in scan_all_dbs because it is called from init function. Otherwise supervisor will kill us.

**Comment by kxepal** [comment]
@iilyak Just a side thought: would move scan_all_dbs from init give any benefit?

**Comment by iilyak** [comment]
@kxepal: I try to avoid complex changes. Otherwise there is a risk that the fix wouldn't be merged due to code freeze.

**Comment by kxepal** [comment]
Ok.

**Comment by nickva** [comment]
@iilyak it is not called and waited on, it is spawn_link-ed from there and shouldn't delay init in either case

 `ScanPid = spawn_link(fun() -> scan_all_dbs(Server) end),`

**Comment by iilyak** [comment]
Right.

**Comment by nickva** [comment]
Thinking about a bit more, it is nicer to have a random sleep in a spawned process as opposed to sleep in-line in scanner, so let's keep that pattern. With an inline sleep it would be hard to reason about a maximum time scanner would run. With spawned processes max would be total time to traverse the fs + max of 1 minute.

**Comment by iilyak** [comment]
> @nickva: Given that replicator_manager is a single bottleneck and will process requests serially anyway (so if it is blocked, resume,... messages will be queued up in its mailbox)

This would be a problem since couch_replication_manager wouldn't be able to handle other types of messages until it would clear all resume_scan messages. It was not a problem before because we didn't do much in `handle_case({resume_scan`. But now we are reading from db and possibly update document.

**Comment by nickva** [comment]
@iilyak agreed, it would block it, there are instances as well, say calculating replication ids when turning replication doc into replication records (id needs a hash of user filter's javascript code, but if network is slow, that would block gen_server and prevent all other requests there from making progress).

We're working on improving that as a separate effort, but that is a bigger restructure. In this case the random sleep approach makes sense -- it should let replicator_manager process some other requests interleaved with `resume` messages

**Comment by nickva** [comment]
+1 with maybe switching to spawn_link

**Pull request merged**
