### PR TITLE
Port HTTP 429 Commits

### PR DESCRIPTION
**Pull request by tonysun83**
These commits allow us to not crash when a server returns a HTTP 429 response during replication.

### CODE REVIEW

**Comment by tonysun83** [comment]
@kxepal: made every macro configurable

**Comment by nickva** [comment]
+1 (after rebase + lower case the config constants). 

I tested with a rate limited account. Changes replicated and made progress. I lowered the max backoff value to see how errors look like. Replications were dying kind of messy sometimes. Depending which request failed, they'd be kill all procs linked to it, showing crashes `{'EXIT',<0.14124.12>,{process_died,<0.14698.12>,...}` but I think that's fine.

Nice job, Tony

**Comment by tonysun83** [comment]
@nickva : thx for the review. rebased and lowered cased the names. do the builds fail sometimes for CI? Log shows 
```
in function couch_changes_tests:'-should_select_with_continuous/1-fun-0-'/1 (test/couch_changes_tests.erl, line 461)
in call from couch_changes_tests:'-should_select_with_continuous/1-fun-3-'/2 (test/couch_changes_tests.erl, line 460)
**error:{assertMatch_failed,[{module,couch_changes_tests},
                     {line,461},
                     {expression,"Rows"},
                     {pattern,"[ # row { seq = 10 , id = << \"doc8\" >> , deleted = false } ]"},
                     {value,[]}]}
```

I just want to be careful before I merge.

**Comment by nickva** [comment]
@tonysun83 I think that is a flaky test, will try it locally see what it does

**Comment by nickva** [comment]
@tonysun83 looks like it is flaky and it is in the couch repo anyway, not even in replicator, so go ahead and merge if you want

**Pull request merged**
