### PR TITLE
restart replications on crash

### PR DESCRIPTION
**Pull request by rnewson**
COUCHDB-2975

### CODE REVIEW

**Comment by kxepal** [comment]
LGFM, +1. Good to see R14 bits away!

**Comment by rnewson** [comment]
@kxepal any thoughts on the restart intensity question?

**Comment by kxepal** [comment]
@rnewson Question? (sorry, I'm out of IRC). Well, it's hard to say for sure without giving a try to find the right values under different situations. I hope you did some research on this already and knows the best. I'm really not sure about this now, sorry ):

**Comment by davisp** [comment]
+1

**Pull request merged**
