### PR TITLE
Handle un-expected closing of pipelined connections better.

### PR DESCRIPTION
**Pull request by nickva**
If during a pipelined connection, server closes its socket,
but http client has more requests to send, ibrowse will
detect that when it sends next request and throw
{error, connection_closing}.

Handle that error better, by closing the socket explicitly
and retrying the pipelined request that failed.

COUCHDB-2833

### CODE REVIEW

**Comment by kxepal** [comment]
I like the fix, but I think it will hide our current issue now. Previously, we didn't suffer from this. Are there any other ways to prevent our own server to close connection when it not supposed to?

**Comment by nickva** [comment]
This is to make our push replication side more robust. It's a good thing the server behaved in this new way, as it let us discover this case.  In theory, replication protocol should be working with other (non-couchdb) servers and it needs to be robust. We can treat the two issues -- "http replication client robustness", and "server closing connection too quickly" as separate.

**Comment by kxepal** [comment]
Yes, I agree with that. My point is that applying this now will hide second issue behind all passed tests.

**Comment by rnewson** [comment]
+1, though we should find out why we get Connection:close for a successful PUT, it's important to reuse sockets when we can.

**Comment by nickva** [comment]
We know how to replicate the issue if we need to -- comment out this patch.

@rnewson  I'll investigate the server next. 

In general servers can choose to close the connection whenever they want, maybe due to concurrency throttling, or say even couchdb behind nginx proxy, it could have a setting to close long lived pipelined requests. It was kind of a nice bonus that changes in the server exposed this bug.

**Comment by davisp** [comment]
+1 to this change and +1 to finding why we're suddenly returning Connection: close for a succesful PUT in another bug. I'd just say that before we close this lets make sure we have a separate test case that reproduces the problem outside the replicator (which sounds easy based on my reading of 2833).

**Comment by rnewson** [comment]
mochiweb is newly sending Connection:close when it determines should_close() is true. mochiweb is right, so I infer that we send some extra garbage in the PUT request (more bytes that Content-Length).

**Comment by davisp** [comment]
Possible.

**Comment by rnewson** [comment]
for a PUT /db/doc where the body has more bytes than Content-Length, couchdb just hangs, so it's not that.

**Comment by rnewson** [comment]
ok, here's how to make mochi send a Connection:close, you need to terminate request handling before we call json_body() (or equivalent). You can achieve that with `PUT /db/doc?open_revs=foo` as the JSON_DECODE of 'foo' will throw. The response will include a Connection:close header, which means any body bytes unread are discarded.

All this is telling us we need a higher level abstraction for our http code.

**Comment by nickva** [comment]
@rnewson @davisp @kxepal 

When processing the request we set mochiweb_request_recv = true in the process dictionary too late. That makes it return Connection: close. ibrowse used to ignore Connection: close and just kept the socket open. Then ibrowse was fixed and revealed the issue.

Here is a potential fix and the details: https://issues.apache.org/jira/browse/COUCHDB-2834

**Pull request merged**
