### PR TITLE
Duplicate jobs transition directly to completed state

### PR DESCRIPTION
**Pull request by rnewson**
_replicate is idempotent but _replicator is not, one can create any
number of documents with the same content. The burden of retrying all
the duplicates can be excessive.

A detected duplicate will now transition immediately to completed, as
we know there's a currently running job for the exact same task.

COUCHDB-2842

### CODE REVIEW

**Comment by kxepal** [comment]
+1

**Comment by kxepal** [comment]
On second though, could we provide some field with the reference onto duplicated by document? Should be helpful.

**Comment by rnewson** [comment]
yes, good idea.

**Comment by kxepal** [comment]
What do you think about to introduce "duplicate" state as synonym to "completed" and the reason for it will be other doc id?

**Comment by rnewson** [comment]
hm, no strong feeling either way except that it complicates things a bit more.

We need a new replicator anyway, and we should address the state transition diagram. I want to see some classes of "error" state become terminal (not retried), so I'd defer to that time. "error" because "duplicate" should be terminal.

I'm using "completed" because it's the only terminal state right now.

**Comment by rnewson** [comment]
This doesn't work if the docs land in different shards, which is more likely than not.

**Comment by rnewson** [comment]
well, not shards, it's if it's "owned" by a different node. the duplication is only detected within the node.

**Comment by kxepal** [comment]
Oh, that's a pity ):

**Comment by rnewson** [comment]
Indeed. It's regrettable that we didn't force the _id to be the replication_id, which would have prevented duplications.

**Pull request closed without merging**
