### PR TITLE
Avoid logging creds on couch_replicator termination

### PR DESCRIPTION
**Pull request by mikewallace1979**
When couch_replicator terminates with an error we log the #rep
record which can contain credentials for the source or target
of a replication, either in the url directly or in an Authorization
header.

This commit adds a function to strip credentials from the #httpdb
records in the #rep record and replace them with ****.

Specifically this concerns the url and headers fields of the
 #rep.source and #rep.target #httpdb records.

Closes COUCHDB-2949

### CODE REVIEW

**Comment by kxepal** [comment]
Wouldn't credentials leak [here](https://github.com/apache/couchdb-couch-replicator/pull/25/files#diff-ba1cca81bdc216835256f72cc6a72fa5R560) as well?

**Comment by mikewallace1979** [comment]
> Wouldn't credentials leak here as well?

I *think* we're ok here because `source_name` and `target_name` in the `#rep_state` record have come from [`couch_replicator_api_wrap:db_uri/1`](https://github.com/apache/couchdb-couch-replicator/blob/master/src/couch_replicator.erl#L616-L617) which will either [extract just the dbname](https://github.com/apache/couchdb-couch-replicator/blob/master/src/couch_replicator_api_wrap.erl#L62-L63) or call [`couch_util:url_strip_password/1`](https://github.com/apache/couchdb-couch-replicator/blob/master/src/couch_replicator_api_wrap.erl#L59-L60).

**Comment by kxepal** [comment]
Ah, good then!

**Comment by kxepal** [comment]
LGFM, but don't have a chance to test this.

**Comment by rnewson** [comment]
+1

**Comment by iilyak** [comment]
Could you implement [format_status](http://erlang.org/doc/man/gen_server.html#Module:format_status-2) as well? In order to prevent leakage from a stack trace.

**Pull request merged**
